// Generated by CoffeeScript 1.3.3
(function() {
  var MockingServer, server;

  MockingServer = require('mocking-server').MockingServer;

  server = new MockingServer;

  server.httpsListen({
    key_path: "" + __dirname + "/ssl/theshopkeep.com.key.pem",
    cert_path: "" + __dirname + "/ssl/theshopkeep.com.cert",
    port: 12001
  }, function(e) {});

  console.log('activated!');

}).call(this);
